export default {
    SET_STATE: "SET_STATE",

    LOAD_FORMB_TEMPLATE_REQ: "LOAD_FORMB_TEMPLATE_REQ",
    LOAD_FORMB_TEMPLATE_SUCCESS:"LOAD_FORMB_TEMPLATE_SUCCESS",
    LOAD_FORMB_TEMPLATE_FAILURE: "LOAD_FORMB_TEMPLATE_FAILURE",
  
    UPDATE_FORMB_TEMPLATE_REQ:"UPDATE_FORMB_TEMPLATE_REQ",
    UPDATE_FORMB_TEMPLATE_SUCCESS:"UPDATE_FORMB_TEMPLATE_SUCCESS",
    UPDATE_FORMB_TEMPLATE_FAILURE:"UPDATE_FORMB_TEMPLATE_FAILURE",
  
  }