export default {
    SET_STATE: "SET_STATE",
  
    LOAD_FORMA_TEMPLATE_REQ: "LOAD_FORMA_TEMPLATE_REQ",
    LOAD_FORMA_TEMPLATE_SUCCESS: "LOAD_FORMA_TEMPLATE_SUCCESS",
    LOAD_FORMA_TEMPLATE_FAILURE: "LOAD_FORMA_TEMPLATE_FAILURE",
  
    UPDATE_FORMA_TEMPLATE_REQ: "UPDATE_FORMA_TEMPLATE_REQ",
    UPDATE_FORMA_TEMPLATE_SUCCESS: "UPDATE_FORMA_TEMPLATE_SUCCESS",
    UPDATE_FORMA_TEMPLATE_FAILURE: "UPDATE_FORMA_TEMPLATE_FAILURE",
  
  }