const ACTIONS = {
  SET_STATE: "SET_STATE",

  SET_LISTENER: "SET_LISTENER",

  UNSUBSCRIBE_LISTENER: "UNSUBSCRIBE_LISTENER",

  LOAD_INVITATION_EMAIL_REQUEST: "LOAD_INVITATION_EMAIL_REQUEST",
  LOAD_INVITATION_EMAIL_SUCCESS: "LOAD_INVITATION_EMAIL_SUCCESS",
  LOAD_INVITATION_EMAIL_FAILURE: "LOAD_INVITATION_EMAIL_FAILURE",

  INVITE_EMPLOYEE_REQUEST: "INVITE_EMPLOYEE_REQUEST",
  INVITE_EMPLOYEE_SUCCESS: "INVITE_EMPLOYEE_SUCCESS",
  INVITE_EMPLOYEE_FAILURE: "INVITE_EMPLOYEE_FAILURE",

  MODULES_REQUEST: "MODULES_REQUEST",
  MODULES_SUCCESS: "MODULES_SUCCESS",
  MODULES_FAILURE: "MODULES_FAILURE",

  ALL_MODULES_REQUEST: "ALL_MODULES_REQUEST",
  ALL_MODULES_SUCCESS: "ALL_MODULES_SUCCESS",
  ALL_MODULES_FAILURE: "ALL_MODULES_FAILURE",

  EMPLOYEES_REQUEST: "EMPLOYEES_REQUEST",
  EMPLOYEES_SUCCESS: "EMPLOYEES_SUCCESS",
  EMPLOYEES_FAILURE: "EMPLOYEES_FAILURE",

  EMPLOYEE_REGISTRATION_REQUEST: "EMPLOYEE_REGISTRATION_REQUEST",
  EMPLOYEE_REGISTRATION_SUCCESS: "EMPLOYEE_REGISTRATION_SUCCESS",
  EMPLOYEE_REGISTRATION_FAILURE: "EMPLOYEE_REGISTRATION_FAILURE",

  LOAD_INVITATED_EMPIFNO_REQUEST: "LOAD_INVITATED_EMPIFNO_REQUEST",
  LOAD_INVITATED_EMPIFNO_SUCCESS: "LOAD_INVITATED_EMPIFNO_SUCCESS",
  LOAD_INVITATED_EMPIFNO_FAILURE: "LOAD_INVITATED_EMPIFNO_FAILURE",
};

export default ACTIONS;
