export const Actions={
    SIGNIN_REQUEST:"SIGININ+REQUEST",
    SIGNIN_SUCCESS:"SIGIN_SUCCESS",
    SIGNIN_FAILURE:"SIGIN_FAILURE",

    SIGNOUT_REQUEST:"SIGOUT_REQUEST",
    SIGNOUT_SUCCESS:"SIGOUT_SUCCESS",
    SIGNOUT_FAILURE:"SIGOUT_FAILURE"
}